In [1]:
import numpy as np
# 1. create arrays
a= np.array([1,2,3,4,5])
print("Array:", a)
print("Shape:", a.shape)

Array: [1 2 3 4 5]
Shape: (5,)


In [4]:
# 2. Zero and Ones
zeros = np.zeros((3,4))
ones = np.ones((2,3))
print("Zeros:", zeros)
print("Ones:", ones)

Zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 3. Range
range_arr = np.arange(1,20,4) # 0 to 10, step 2
print("Range:", range_arr)
linspace = np.linspace(0,23,5)
print("Linspace :", linspace)
eyed = np.eye(4)
print(eyed)
random_seed = np.random.randn(3,3)
print(random_seed)

Range: [ 1  5  9 13 17]
Linspace : [ 0.    5.75 11.5  17.25 23.  ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [5]:
# 4. Arithmetic
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Element-wise sqrt:", np.sqrt(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Element-wise sqrt: [1.         1.41421356 1.73205081]


In [6]:
# 5. 2D Arrays (metrices)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix Shape:", matrix.shape)
print("Matrix:\n", matrix)

Matrix Shape: (2, 3)
Matrix:
 [[1 2 3]
 [4 5 6]]


In [7]:
# 6. Matrix Multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
result = np.dot(A,B) #matrix multiplication
print("Matrix Product \n", result)

Matrix Product 
 [[19 22]
 [43 50]]


In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
arr2 = np.array((1,2,3,4,5,6))
print(arr2)
print(type(arr2))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [7]:
arr3 = np.array([2]) #0-D array of scalar array
arr4 = np.array([1,2,3,4]) # 1-D arrayor un-diamensional array
arr5 = np.array([[1,2,3],[4,5,6]]) #2-D array 
print(arr3)

[2]


In [8]:
print(arr4)


[1 2 3 4]


In [9]:
print(arr5)


[[1 2 3]
 [4 5 6]]


In [10]:
print(arr5.ndim)

2


In [11]:
print(arr4.ndim)


1


In [12]:
arr6 = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
print(arr6)
print(arr6.ndim)


[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]
3


In [13]:
arr7 = np.array([1,2,3,4], ndmin=5)
print(arr7)

[[[[[1 2 3 4]]]]]


In [14]:
print(arr4[3]+arr4[2])

7
