In [1]:
import numpy as np
# 1. create arrays
a= np.array([1,2,3,4,5])
print("Array:", a)
print("Shape:", a.shape)

Array: [1 2 3 4 5]
Shape: (5,)


In [2]:
# 2. Zero and Ones
zeros = np.zeros(5)
ones = np.ones(3)
print("Zeros:", zeros)
print("Ones:", ones)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1.]


In [4]:
# 3. Range
range_arr = np.arange(0,10,2) # 0 to 10, step 2
print("Range:", range_arr)

Range: [0 2 4 6 8]


In [5]:
# 4. Arithmetic
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Element-wise sqrt:", np.sqrt(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Element-wise sqrt: [1.         1.41421356 1.73205081]


In [6]:
# 5. 2D Arrays (metrices)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix Shape:", matrix.shape)
print("Matrix:\n", matrix)

Matrix Shape: (2, 3)
Matrix:
 [[1 2 3]
 [4 5 6]]


In [7]:
# 6. Matrix Multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
result = np.dot(A,B) #matrix multiplication
print("Matrix Product \n", result)

Matrix Product 
 [[19 22]
 [43 50]]
